language: node_js

node_js:
- 14

before_deploy:
- npm install
- npm install -g vsce

deploy:
- provider: script
  script: vsce publish -p $VS_TOKEN
  skip_cleanup: true
  on:
    repo: warcraft-iii/warcraft-vscode
    branch: master
    tags: true
